### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by KappaMund** [rohitgandikota/sliders#14]
When trying to run a command to train SD-XL:
**`python trainscripts/textsliders/train_lora_xl.py --attributes 'male, female' --name 'agesliderXL' --rank 4 --alpha 1 --config_file 'data/config-xl.yaml`**

An error occurs:

`(sliders) C:\!NeuralNetwork\sliders>python trainscripts/textsliders/train_lora_xl.py --attributes 'male, female' --name 'agesliderXL' --rank 4 --alpha 1 --config_file 'data/config-xl.yaml
Traceback (most recent call last):
  File "C:\!NeuralNetwork\sliders\trainscripts\textsliders\train_lora_xl.py", line 18, in <module>
    import prompt_util
  File "C:\!NeuralNetwork\sliders\trainscripts\textsliders\prompt_util.py", line 44, in <module>
    class PromptSettings(BaseModel):  # yaml のやつ
  File "pydantic\main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Aleksandr.Antropov\AppData\Local\miniconda3\envs\sliders\lib\typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class`
![image](https://github.com/rohitgandikota/sliders/assets/140675665/a15f5f85-b033-44dd-a06a-80d9fc3f1651)

Setting the environment and requirements.txt were executed verbatim: 
> conda create -n sliders python=3.9
> conda activate sliders
> 
> git  clone https://github.com/rohitgandikota/sliders.git
> cd sliders
> pip install -r requirements.txt

There were no errors during the installation of dependencies.

**Comment by rohitgandikota** [comment]
looks like a pydantic package issue. Our local version is 1.10.3

also - the command should be `python trainscripts/textsliders/train_lora_xl.py --attributes 'male, female' --name 'agesliderXL' --rank 4 --alpha 1 --config_file 'trainscripts/textsliders/data/config-xl.yaml'`

**Comment by KappaMund** [comment]
The problem persists.
Locally installed pydantic==1.10.3

`(sliders) C:\!NeuralNetwork\sliders>python trainscripts/textsliders/train_lora_xl.py --attributes 'male, female' --name 'agesliderXL' --rank 4 --alpha 1 --config_file 'trainscripts/textsliders/data/config-xl.yaml'
Traceback (most recent call last):
  File "C:\!NeuralNetwork\sliders\trainscripts\textsliders\train_lora_xl.py", line 18, in <module>
    import prompt_util
  File "C:\!NeuralNetwork\sliders\trainscripts\textsliders\prompt_util.py", line 44, in <module>
    class PromptSettings(BaseModel):  # yaml のやつ
  File "pydantic\main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Aleksandr.Antropov\AppData\Local\miniconda3\envs\sliders\lib\typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class`

![image](https://github.com/rohitgandikota/sliders/assets/140675665/0a3acc2d-ea32-4579-9262-b891bbca5dde)

**Comment by rohitgandikota** [comment]
Found this on stackoverflow
```
As @Domi W suggested in one of the comments, this is what worked for me and solved my issues with feast complaining about TypeError: issubclass() arg 1 must be a class:

pip install --force-reinstall typing-extensions==4.5.0
```

**Comment by KappaMund** [comment]
**It definitely helped!**

But there was another problem related to arguments.
`(sliders) C:\!NeuralNetwork\sliders>python trainscripts/textsliders/train_lora_xl.py --attributes 'male, female' --name 'agesliderXL' --rank 4 --alpha 1 --config_file 'trainscripts/textsliders/data/config-xl.yaml'
usage: train_lora_xl.py [-h] --config_file CONFIG_FILE --alpha ALPHA [--rank RANK] [--device DEVICE] [--name NAME]
                        [--attributes ATTRIBUTES]
train_lora_xl.py: error: unrecognized arguments: female'`

![image](https://github.com/rohitgandikota/sliders/assets/140675665/50e394a7-661a-4142-81c8-854bdac9a863)

**Comment by rohitgandikota** [comment]
huh - looks like a windows thing? maybe make all the front slashes to double back slashes `/` to `\\`

**Comment by quixot1c** [comment]
maybe try using Powershell, sd1.5 scripts work for me with that way of passing --attributes

**Comment by rohitgandikota** [comment]
Awesome! Thanks @ThereforeGames  and @quixot1c!

@KappaMund, closing the issue. Please feel free to reopen if the issue persists. Thanks!
