### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by pondloso** [rohitgandikota/sliders#22]
I just quick test  and it give me this error

(sliders) F:\slider lora\sliders>python trainscripts/textsliders/train_lora.py --attributes 'male, female' --name 'ageslider' --rank 4 --alpha 1 --config_file 'trainscripts/textsliders/data/config.yaml'
Traceback (most recent call last):
  File "F:\slider lora\sliders\trainscripts\textsliders\train_lora.py", line 18, in <module>
    import prompt_util
  File "F:\slider lora\sliders\trainscripts\textsliders\prompt_util.py", line 44, in <module>
    class PromptSettings(BaseModel):  # yaml のやつ
  File "pydantic\main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by rohitgandikota** [comment]
https://github.com/rohitgandikota/sliders/issues/14

**Comment by pondloso** [comment]
sorry my bad not see old issue.

Now i got this error T
raceback (most recent call last):
  File "F:\slider lora\sliders\trainscripts\textsliders\train_lora_xl.py", line 463, in <module>
    main(args)
  File "F:\slider lora\sliders\trainscripts\textsliders\train_lora_xl.py", line 411, in main
    train(config, prompts, device)
  File "F:\slider lora\sliders\trainscripts\textsliders\train_lora_xl.py", line 80, in train
    unet.enable_xformers_memory_efficient_attention()
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\site-packages\diffusers\models\modeling_utils.py", line 262, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\site-packages\diffusers\models\modeling_utils.py", line 226, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\site-packages\diffusers\models\modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\site-packages\diffusers\models\modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\site-packages\diffusers\models\modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\site-packages\diffusers\models\modeling_utils.py", line 219, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\site-packages\diffusers\models\modeling_utils.py", line 226, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\site-packages\diffusers\models\modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\site-packages\diffusers\models\modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\site-packages\diffusers\models\modeling_utils.py", line 219, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\Users\Pond\anaconda3\envs\sliders\lib\site-packages\diffusers\models\attention_processor.py", line 193, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers


....
In requirements i'm not see xformers or because my GPU not had enough memory?

**Comment by rohitgandikota** [comment]
yes, we are working on the xformers support. Currently I don't think it would work. In the meantime, set the xformers flag to `False` in the config file

**Comment by pondloso** [comment]
Thank you for your help it all work, but too bad is not enough memory for me to train seem like it really need  xformers support.

**Comment by rohitgandikota** [comment]
On it! Planning to release an update next week with xformers

**Comment by rohitgandikota** [comment]
meantime, to run the training - 
1. in config, you can use weight type as float 16
2. Instead of loading everything to GPU (eg. `positive_latents`, `unconditional_latents`, ...) you can load them to CPU instead. The script automatically should take care of devices even you load them to CPU in `train_lora.py`

**Comment by pondloso** [comment]
Thank you. can't wait for  xformers support 
I really love to train some my lora idea your sample slider is really game changer 
It a shame if it get block by high memory  use.

**Comment by quixot1c** [comment]
I had that error too, installed xformers as per the facebook link in the error, and it started working.

**Comment by rohitgandikota** [comment]
> Thank you. can't wait for xformers support I really love to train some my lora idea your sample slider is really game changer It a shame if it get block by high memory use.

xformers is enabled now! You can try it out
