### ISSUE TITLE
channels issue

### ISSUE THREAD

**Issue by audwns1gh** [rohitgandikota/sliders#42]
Hi. I tried to train with an imageslider, but the training failed to start with this error. Also, the training model did not change from SD1.4. The training environment was run in Runpod (Linux). What am I doing wrong?

  0%|                                                                                                                                                                                          | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/sliders/trainscripts/imagesliders/train_lora-scale.py", line 501, in <module>
    main(args)
  File "/workspace/sliders/trainscripts/imagesliders/train_lora-scale.py", line 419, in main
    train(config=config, prompts=prompts, device=device, folder_main = args.folder_main, folders = folders, scales = scales)
  File "/workspace/sliders/trainscripts/imagesliders/train_lora-scale.py", line 225, in train
    denoised_latents_low, low_noise = train_util.get_noisy_image(
  File "/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/sliders/trainscripts/imagesliders/train_util.py", line 221, in get_noisy_image
    init_latents = vae.encode(image).latent_dist.sample(None)
  File "/venv/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/venv/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 242, in encode
    h = self.encoder(x)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/diffusers/models/vae.py", line 111, in forward
    sample = self.conv_in(sample)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 4, 256, 256] to have 3 channels, but got 4 channels instead
root@64ea1ab8d463:/workspace/sliders#

**Comment by andreamoreto** [comment]
Convert your training images from png to jpg and it should work.

**Comment by rohitgandikota** [comment]
Yeah, your training images have 4 channels. So you can simply exclude the fourth channel like this:

```
im = Image.open(path_to_image)
im_array = np.array(im)
if im_array.shape[-1] == 4:
     im_restored = Image.fromarray(im_array[:,:,:3])
     im_restored.save(path_to_image)
```
or simply
```
im = Image.open(path_to_image).convert('RGB')
im.save(path_to_image)
```

As @andreamoreto suggested - saving it as `.png` might do the trick (although I have not tried it myself)

**Comment by audwns1gh** [comment]
Thanks, I see that the fourth channel is referring to alpha channel.

**Comment by rohitgandikota** [comment]
yes! glad it worked! Closing the issue
