### ISSUE TITLE
Help with Training Error

### ISSUE THREAD

**Issue by xrxlkool** [rohitgandikota/sliders#73]
I'm not a coding expert by any means, so I need some help troubleshooting this error when starting the training:

Traceback (most recent call last):
  File "C:\Emulator\AI\LECO\sliders\trainscripts\textsliders\train_lora.py", line 419, in <module>
    main(args)
  File "C:\Emulator\AI\LECO\sliders\trainscripts\textsliders\train_lora.py", line 364, in main
    train(config=config, prompts=prompts, device=device)
  File "C:\Emulator\AI\LECO\sliders\trainscripts\textsliders\train_lora.py", line 57, in train
    tokenizer, text_encoder, unet, noise_scheduler = model_util.load_models(
  File "C:\Emulator\AI\LECO\sliders\trainscripts\textsliders\model_util.py", line 114, in load_models
    tokenizer, text_encoder, unet = load_checkpoint_model(
  File "C:\Emulator\AI\LECO\sliders\trainscripts\textsliders\model_util.py", line 83, in load_checkpoint_model
    pipe = StableDiffusionPipeline.from_ckpt(
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\loaders.py", line 1723, in from_ckpt
    return cls.from_single_file(*args, **kwargs)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\loaders.py", line 1922, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1534, in download_from_original_stable_diffusion_ckpt
    text_model = convert_ldm_clip_checkpoint(
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 802, in convert_ldm_clip_checkpoint
    set_module_tensor_to_device(text_model, param_name, "cpu", value=param)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\utils\modeling.py", line 115, in set_module_tensor_to_device
    new_module = getattr(module, split)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CLIPTextModel' object has no attribute 'embeddings'

**Comment by rohitgandikota** [comment]
Hey! Of course! I am happy to help. 

Can you share some more details? What model are you using to train the sliders? Did you install the requirements as described in the setup from the README?

**Comment by xrxlkool** [comment]
Yes, I did install the requirements from the setup info and there seemed to be no issues. Then, I tried using nai.safetensors to train which was what created the original error. I also tried using the SD1.5 checkpoint which generated this error:

Traceback (most recent call last):
  File "C:\Emulator\AI\LECO\sliders\trainscripts\textsliders\train_lora.py", line 419, in <module>
    main(args)
  File "C:\Emulator\AI\LECO\sliders\trainscripts\textsliders\train_lora.py", line 364, in main
    train(config=config, prompts=prompts, device=device)
  File "C:\Emulator\AI\LECO\sliders\trainscripts\textsliders\train_lora.py", line 64, in train
    text_encoder.to(device, dtype=weight_dtype)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 1811, in to
    return super().to(*args, **kwargs)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by rohitgandikota** [comment]
Aah, thanks for the information! So the first error was because the safetensors you provided doesn't have all the modules for the diffusion model. They need to have tokenizer, text encoder, unet, and vae.

Now this error will go away when you give it a huggingface model because they contain all these modules. And it did! But turns out you were trying to run the code on a gpu when either your machine doesn't have a supporting gpu or your installations were not done on gpu. I'm guessing that you are running on a non-gpu machine. 

You can try on platforms that provide free gpus like colab. Or you can try out our demo on huggingface where you can get a free gpu to run. Although with the demo, I'm afraid you can't use custom models.

**Comment by xrxlkool** [comment]
Thanks for the help, I definitely have a GPU (3080 TI), so it's odd that you say that's the issue. Is there something I could have done wrong during the installation/setup process? I simply created a folder, opened a cmd prompt within that folder, and then pasted/executed the setup prompt provided.

I'll give the other options you provided a try as well.

**Comment by keclee** [comment]
I had this exact issue. It was solved with this Reddit post. I had the CPU torch version installed instead of the GPU version.
https://www.reddit.com/r/StableDiffusion/comments/15bxuhw/automatic_1111_pytorch_201cu118_with_cuda_1108/

Overwriting torch 2.0.1+cpu & installing torch 2.0.1+cu118 fixed the issue.
Ran this command in the sliders directory.
`python -m pip install torch==2.0.1+cu118 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`
