### ISSUE TITLE
ValueError: Incompatible shapes for attention inputs:

### ISSUE THREAD

**Issue by SytanSD** [rohitgandikota/sliders#86]
Error is as follows:
```  0%|                                                                                          | 0/250 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\WindowsSliders\sliders-for-windows-qinglong\trainscripts\imagesliders\train_lora-scale.py", line 545, in <module>
    main(args)
  File "E:\WindowsSliders\sliders-for-windows-qinglong\trainscripts\imagesliders\train_lora-scale.py", line 456, in main
    train(
  File "E:\WindowsSliders\sliders-for-windows-qinglong\trainscripts\imagesliders\train_lora-scale.py", line 291, in train
    high_latents = train_util.predict_noise(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\trainscripts\imagesliders\train_util.py", line 160, in predict_noise
    noise_pred = unet(
                 ^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\diffusers\models\unet_2d_condition.py", line 930, in forward
    sample, res_samples = downsample_block(
                          ^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1053, in forward
    hidden_states = attn(
                    ^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\diffusers\models\transformer_2d.py", line 309, in forward
    hidden_states = block(
                    ^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\diffusers\models\attention.py", line 215, in forward
    attn_output = self.attn2(
                  ^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\diffusers\models\attention_processor.py", line 322, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\diffusers\models\attention_processor.py", line 1034, in __call__
    hidden_states = xformers.ops.memory_efficient_attention(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\xformers\ops\fmha\__init__.py", line 223, in memory_efficient_attention
    return _memory_efficient_attention(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\xformers\ops\fmha\__init__.py", line 321, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\xformers\ops\fmha\__init__.py", line 334, in _memory_efficient_attention_forward
    inp.validate_inputs()
  File "E:\WindowsSliders\sliders-for-windows-qinglong\venv\Lib\site-packages\xformers\ops\fmha\common.py", line 197, in validate_inputs
    raise ValueError(
ValueError: Incompatible shapes for attention inputs:
  query.shape: torch.Size([16, 1024, 40])
  key.shape  : torch.Size([128, 77, 40])
  value.shape: torch.Size([128, 77, 40])
HINT: We don't support broadcasting, please use `expand` yourself before calling `memory_efficient_attention` if you need to
```

Not sure how to fix this, I am unsure of if this is referring to my input imaging being too high res or not. Any help would be greatly appreciated

**Comment by rohitgandikota** [comment]
This could be for couple of reasons. 
1. I would check the size of your images. Sometimes jpeg saves a 4 channel image rather than the standard 3 channel (rgb). You can look into that and correct some shapes
2. Maybe try disabling the memory efficient attention? That could be causing this too

Can you look at these and let me know if it helped?

**Comment by keclee** [comment]
I had the same problem. I believe it was caused by having batch size > 1 for image sliders.

**Comment by Farenweh** [comment]
mem_efficient_attn seems do NOT work when len(k) != len(q)!, so padding your k sequence or get a substitute attn.

**Comment by rohitgandikota** [comment]
closing the issue due to inactivity. Please reopen if the same issue persists. Thanks everyone!
